macro(sub_dir_list result cur_dir)
    file(GLOB children RELATIVE ${cur_dir} ${cur_dir}/*)
    set(dirlist "")
    foreach(child ${children})
        if (IS_DIRECTORY ${cur_dir}/${child})
	    list(APPEND dir_list ${child})
	endif()
    endforeach()
    set(${result} ${dir_list})
endmacro()
